
version: "2.3"
services:
  nginx:
    build: . 
    container_name: nginx
    volumes:
      - ./public:/root/public
    ports:
      - 8081:80
    pid: host
    restart: always
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia